### ISSUE TITLE
text/image vs. stream of points

### ISSUE THREAD

**Issue by randycasburn** [magicien/undo-canvas#1]
Nice work! Well done. I came here because I couldn't find an easy answer to this dilemma either:

1. User story: As a canvas user I want to click a single button so that I can undo an action
2. User story: As a canvas user I want to click a single button so that I can redo an action

#### How does one to determine the use of "undo/redo" or "undoTag/redoTag"? 

There are two different workflows:
1. Undo/redo of a single artifact of streaming points
  - Such as a line or rectangle (what you call a tag) 
  - Click the UndoTag and the RedoTag. 
2. Undo/redo a single non-streaming entity
  - Such as Text or an Image
 - Click the Undo and Redo

Breaks the user stories.

To reproduce: 
* open the attached modified demo2.html file
* click add text button
* click add image button
* draw a line
* undo/redo each

[demo2.html.zip](https://github.com/magicien/undo-canvas/files/1636371/demo2.html.zip)

I haven't looked deeply at your code, I just put this demo together to see if you had solved this issue. If there is an easy programatic fix please let me know.

**Comment by magicien** [comment]
Hi! Thank you for trying!

Sorry for the lack of documentation.
I think undoTag/redoTag should be used in most cases.

UndoCanvas doesn't put tags automatically,
so users should decide where to put a tag.
You can use `context.putTag()` to set a tag to the currenct state.

If you put `context.putTag()` right after `context.fillText('This is a test', 20, 20);` and `context.drawImage(img, 10,10, 20,20);`, it will work as you expected.

**Comment by randycasburn** [comment]
Didn't grock that at all!  Thanks for the quick response and explanation.

**Comment by gilthunderness** [comment]
lets hope someone see this comment, hello.
I was hoping if its possible to get all the current colours present on the canvas at a given moment?
